"""Step 8 of the runtime-scaling benchmark (reviewer 1 response).

Generate FOUR pgfplots/TikZ figures (copy-paste ready for LaTeX):

    {pre-order, partial-order} x {Hamming, Subset}

Each figure has:
  * the four main solver curves (GLPK / HiGHS x full / height=2),
  * one dashed power-law TREND line per curve, labelled with its fitted
    exponent K^x (drawn across the full K range so GLPK's trend is visible
    even where it is too slow to measure),
  * horizontal baseline lines (BR, CC, CLR, ECC),
  * axis labelled in K (paper notation), log-log, NO interior grid.

Writes each figure as a standalone .tex (the inner tikzpicture is what you
paste into the paper) and, if a LaTeX toolchain is present, compiles a .pdf +
.png preview.
"""

import csv
import pickle
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

SCRATCH = Path("/tmp/claude-24679/-home-s2320437-WORK-preorder4MLC/"
               "1acafedf-6413-4348-9250-5e9e5557bcc1/scratchpad")
OUTDIR = Path("/home/s2320437/WORK/preorder4MLC/docs/reviewer_response/tikz")
OUTDIR.mkdir(parents=True, exist_ok=True)

CSV = {
    "preorder": SCRATCH / "scaling_results.csv",
    "partial": SCRATCH / "scaling_results_partial.csv",
}
ORDER_TITLE = {"preorder": "pre-order", "partial": "partial order"}
METRIC_TITLE = {"Hamming": "Hamming accuracy",
                "Subset": "Subset (0/1 exact-match) accuracy"}

# main curves: (solver, height) -> (tikz color, mark, legend)
CURVES = [
    ("glpk", "full", "red!75!black", "*", "GLPK, full transitivity"),
    ("glpk", "h2", "orange!90!black", "square*", "GLPK, height=2"),
    ("highs", "full", "blue!70!black", "*", "HiGHS, full transitivity"),
    ("highs", "h2", "cyan!70!black", "square*", "HiGHS, height=2"),
]
BASELINES = [
    ("BR", "green!55!black", "Binary Relevance (BR)"),
    ("CC", "teal", "Classifier Chain (CC)"),
    ("CLR", "violet", "Calibrated Label Ranking (CLR)"),
    ("ECC", "brown", "Ensemble of Classifier Chains (ECC)"),
]
KGRID = [6, 10, 14, 19, 25, 31, 37, 45, 53]


def load_rows(path):
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            r["L"] = int(r["L"])
            r["mean_solve_s"] = float(r["mean_solve_s"])
            rows.append(r)
    return rows


def curve(rows, solver, height, metric):
    sel = [r for r in rows if r["solver"] == solver
           and r["height"] == height and r["metric"] == metric]
    Ks = sorted({r["L"] for r in sel})
    ys = [next(r["mean_solve_s"] for r in sel if r["L"] == K) * 1e3 for K in Ks]
    return np.array(Ks, dtype=float), np.array(ys)


def fit(Ks, ys):
    slope, intercept = np.polyfit(np.log(Ks), np.log(ys), 1)
    return slope, np.exp(intercept)   # y = coeff * K^slope


def make_tikz(order, metric, rows, meta):
    lines = []
    P = lines.append
    P("% Auto-generated by scripts/bench_step8_tikz.py -- requires \\usepackage{pgfplots}")
    P("\\begin{tikzpicture}")
    P("\\begin{loglogaxis}[")
    P("    width=10cm, height=7.5cm,")
    P("    xlabel={Number of labels $K$}, ylabel={Avg.\\ time per instance (ms)},")
    P(f"    title={{{ORDER_TITLE[order]}, {METRIC_TITLE[metric]}}},")
    # x ticks as plain integers; y ticks stay in 10^k exponent form
    P("    xtick={6,10,14,19,25,31,37,45,53},")
    P("    xticklabels={6,10,14,19,25,31,37,45,53},")
    P("    grid=none,")   # no interior grid (requested)
    P("    xminorticks=false, yminorticks=false,")   # no log minor tick marks
    P("    axis x line*=bottom, axis y line*=left,")  # drop top/right frame
    P("    legend pos=north west, legend cell align=left,")
    P("    legend style={font=\\tiny, inner sep=1pt, row sep=-1pt},")
    P("    xmin=5.5, xmax=60,")
    P("]")

    # baselines first (behind the curves); labels parked at the right edge,
    # above each dotted line, where the (high) solver curves never reach.
    for name, color, _ in BASELINES:
        y = meta["baseline_per_instance_s"][name] * 1e3
        P(f"\\addplot[{color}, dotted, thick, forget plot, domain=6:53, samples=2] {{{y:.4g}}};")
        P(f"\\node[{color}, font=\\tiny, anchor=south east] at (axis cs:53,{y:.4g}) "
          f"{{{name} {y:.1f} ms}};")

    # main curves; the fitted exponent goes into the legend, and a dashed
    # trend line of that slope is drawn across the full K range (so GLPK's
    # trend is visible even where it is too slow to measure).
    for solver, height, color, mark, legend in CURVES:
        Ks, ys = curve(rows, solver, height, metric)
        if len(Ks) == 0:
            continue
        coords = " ".join(f"({int(k)},{v:.5g})" for k, v in zip(Ks, ys))
        slope, coeff = fit(Ks, ys)
        P(f"\\addplot[{color}, mark={mark}, thick] coordinates {{{coords}}};")
        P(f"\\addlegendentry{{{legend} ($\\propto K^{{{slope:.1f}}}$)}}")
        P(f"\\addplot[{color}, dashed, forget plot, domain=6:53, samples=2] "
          f"{{{coeff:.6g}*x^{slope:.4f}}};")

    P("\\end{loglogaxis}")
    P("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


def compile_preview(stem, tikz):
    if shutil.which("pdflatex") is None:
        return False
    doc = ("\\documentclass[border=4pt]{standalone}\n"
           "\\usepackage{pgfplots}\\pgfplotsset{compat=1.16}\n"
           "\\begin{document}\n" + tikz + "\\end{document}\n")
    with tempfile.TemporaryDirectory() as td:
        tex = Path(td) / f"{stem}.tex"
        tex.write_text(doc)
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                            "-halt-on-error", tex.name], cwd=td,
                           capture_output=True, text=True)
        pdf = Path(td) / f"{stem}.pdf"
        if not pdf.exists():
            print(f"  ! pdflatex failed for {stem}:\n"
                  + "\n".join(r.stdout.splitlines()[-15:]))
            return False
        shutil.copy(pdf, OUTDIR / f"{stem}.pdf")
        if shutil.which("pdftoppm"):
            subprocess.run(["pdftoppm", "-png", "-r", "150",
                           str(OUTDIR / f"{stem}.pdf"),
                           str(OUTDIR / stem)], capture_output=True)
            # pdftoppm appends -1; normalise the name
            p1 = OUTDIR / f"{stem}-1.png"
            if p1.exists():
                p1.rename(OUTDIR / f"{stem}.png")
        return True


def main():
    meta = pickle.load((SCRATCH / "enron_bench_meta.pkl").open("rb"))
    for order in ("preorder", "partial"):
        rows = load_rows(CSV[order])
        for metric in ("Hamming", "Subset"):
            stem = f"runtime_{order}_{metric.lower()}"
            tikz = make_tikz(order, metric, rows, meta)
            (OUTDIR / f"{stem}.tex").write_text(tikz)
            ok = compile_preview(stem, tikz)
            print(f"wrote {stem}.tex" + ("  + preview png/pdf" if ok else ""))


if __name__ == "__main__":
    main()
