"""Step 8 of the runtime-scaling benchmark (reviewer 1 response).

Generate FOUR pgfplots/TikZ figures (copy-paste ready for LaTeX):

    {pre-order, partial-order} x {Hamming, Subset}

Each figure has:
  * the four main solver curves (GLPK / HiGHS x full / height=2),
  * one dashed power-law TREND line per curve, labelled with its fitted
    exponent K^x (drawn across the full K range so GLPK's trend is visible
    even where it is too slow to measure),
  * horizontal baseline lines (BR, CC, CLR, ECC),
  * axis labelled in K (paper notation), log-log, NO interior grid.

Writes each figure as a standalone .tex (the inner tikzpicture is what you
paste into the paper) and, if a LaTeX toolchain is present, compiles a .pdf +
.png preview.
"""

import csv
import pickle
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

SCRATCH = Path("/tmp/claude-24679/-home-s2320437-WORK-preorder4MLC/"
               "1acafedf-6413-4348-9250-5e9e5557bcc1/scratchpad")
OUTDIR = Path("/home/s2320437/WORK/preorder4MLC/docs/reviewer_response/tikz")
OUTDIR.mkdir(parents=True, exist_ok=True)

CSV = {
    "preorder": SCRATCH / "scaling_results.csv",
    "partial": SCRATCH / "scaling_results_partial.csv",
}
ORDER_TITLE = {"preorder": "pre-order", "partial": "partial order"}
METRIC_TITLE = {"Hamming": "Hamming accuracy",
                "Subset": "Subset (0/1 exact-match) accuracy"}

# main curves: (solver, height) -> (tikz color, mark, legend)
CURVES = [
    ("glpk", "full", "red!75!black", "*", "GLPK, full transitivity"),
    ("glpk", "h2", "orange!90!black", "square*", "GLPK, height=2"),
    ("highs", "full", "blue!70!black", "*", "HiGHS, full transitivity"),
    ("highs", "h2", "cyan!70!black", "square*", "HiGHS, height=2"),
]
BASELINES = [
    ("BR", "green!55!black", "Binary Relevance (BR)"),
    ("CC", "teal", "Classifier Chain (CC)"),
    ("CLR", "violet", "Calibrated Label Ranking (CLR)"),
    ("ECC", "brown", "Ensemble of Classifier Chains (ECC)"),
]
# Set False (or delete the emitted \node lines in the .tex) to drop the
# "BR 2.5 ms" style labels next to each dotted baseline; the lines stay.
SHOW_BASELINE_LABELS = True
BASELINE_LABEL_FONT = "\\fontsize{4}{5}\\selectfont"   # smaller than \tiny
KGRID = [6, 10, 14, 19, 25, 31, 37, 45, 53]


def load_rows(path):
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            r["L"] = int(r["L"])
            r["mean_solve_s"] = float(r["mean_solve_s"])
            rows.append(r)
    return rows


def curve(rows, solver, height, metric):
    sel = [r for r in rows if r["solver"] == solver
           and r["height"] == height and r["metric"] == metric]
    Ks = sorted({r["L"] for r in sel})
    ys = [next(r["mean_solve_s"] for r in sel if r["L"] == K) * 1e3 for K in Ks]
    return np.array(Ks, dtype=float), np.array(ys)


def fit(Ks, ys):
    slope, intercept = np.polyfit(np.log(Ks), np.log(ys), 1)
    return slope, np.exp(intercept)   # y = coeff * K^slope


def value_at_53(rows, solver, height, metric):
    """Per-instance time (ms) at K=53: measured if present, else the
    least-squares power-law extrapolation (flagged True)."""
    Ks, ys = curve(rows, solver, height, metric)
    if len(Ks) == 0:
        return None, False
    Ki = list(Ks.astype(int))
    if 53 in Ki:
        return ys[Ki.index(53)], False
    slope, coeff = fit(Ks, ys)
    return coeff * 53.0 ** slope, True


def fmt_ms(v):
    if v >= 1e4:
        return f"{v:,.0f}"
    if v >= 100:
        return f"{v:.0f}"
    return f"{v:.1f}"


def make_tikz(order, metric, rows, meta):
    lines = []
    P = lines.append
    P("% Auto-generated by scripts/bench_step8_tikz.py -- requires \\usepackage{pgfplots}")
    P("\\begin{tikzpicture}")
    P("\\begin{loglogaxis}[")
    P("    width=10cm, height=7.5cm,")
    P("    xlabel={Number of labels $K$}, ylabel={Avg.\\ time per instance (ms)},")
    P(f"    title={{{ORDER_TITLE[order]}, {METRIC_TITLE[metric]}}},")
    # x ticks as plain integers; y ticks stay in 10^k exponent form
    P("    xtick={6,10,14,19,25,31,37,45,53},")
    P("    xticklabels={6,10,14,19,25,31,37,45,53},")
    P("    grid=none,")   # no interior grid (requested)
    P("    xminorticks=false, yminorticks=false,")   # no log minor tick marks
    P("    axis x line*=bottom, axis y line*=left,")  # drop top/right frame
    P("    legend pos=north west, legend cell align=left,")
    P("    legend style={font=\\tiny, inner sep=1pt, row sep=-1pt},")
    P("    xmin=5.5, xmax=60,")
    P("]")

    # baselines first (behind the curves); labels parked at the right edge,
    # above each dotted line, where the (high) solver curves never reach.
    for name, color, _ in BASELINES:
        y = meta["baseline_per_instance_s"][name] * 1e3
        P(f"\\addplot[{color}, dotted, thick, forget plot, domain=6:53, samples=2] {{{y:.4g}}};")
        if SHOW_BASELINE_LABELS:
            P(f"\\node[{color}, font={BASELINE_LABEL_FONT}, anchor=south east] "
              f"at (axis cs:53,{y:.4g}) {{{name} {y:.1f} ms}};")

    # main curves; each gets a colour-matched dashed power-law line c*K^x whose
    # exponent x AND coefficient c come from a least-squares fit of log(time)
    # vs log(K) for THAT method. On log-log this dashed line is a straight line
    # of slope x sitting over its own curve, so its closeness shows how well a
    # pure power law describes the method. The fitted x is echoed in the legend.
    for solver, height, color, mark, legend in CURVES:
        Ks, ys = curve(rows, solver, height, metric)
        if len(Ks) == 0:
            continue
        coords = " ".join(f"({int(k)},{v:.5g})" for k, v in zip(Ks, ys))
        slope, coeff = fit(Ks, ys)
        # dashed fitted K^x line first (behind the measured markers), drawn
        # across the full K range so GLPK's trend shows past its measured cap.
        P(f"\\addplot[{color}, dashed, forget plot, domain=6:53, samples=2] "
          f"{{{coeff:.6g}*x^{slope:.4f}}};")
        P(f"\\addplot[{color}, mark={mark}, thick] coordinates {{{coords}}};")
        P(f"\\addlegendentry{{{legend} ($\\propto K^{{{slope:.1f}}}$)}}")

    P("\\end{loglogaxis}")
    P("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


TABLE_COLS = [("preorder", "Hamming"), ("preorder", "Subset"),
              ("partial", "Hamming"), ("partial", "Subset")]


def make_table(all_rows, meta):
    """LaTeX table of per-instance inference time at K=53 for every method
    across the four figures. Returns (full_table_tex, tabular_only_for_preview)."""
    body = []
    B = body.append
    B("\\begin{tabular}{lrrrr}")
    B("\\toprule")
    B(" & \\multicolumn{2}{c}{pre-order} & \\multicolumn{2}{c}{partial order}"
      " \\\\")
    B("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}")
    B("Method & Hamming & Subset & Hamming & Subset \\\\")
    B("\\midrule")
    for solver, height, _color, _mark, legend in CURVES:
        cells = []
        for order, metric in TABLE_COLS:
            v, extrapolated = value_at_53(all_rows[order], solver, height, metric)
            if extrapolated:                      # avoid false precision
                d = int(np.floor(np.log10(v)))
                v = round(v, -(d - 1))            # 2 significant figures
            cells.append(fmt_ms(v) + ("\\textsuperscript{*}" if extrapolated
                                      else ""))
        B(f"{legend} & " + " & ".join(cells) + " \\\\")
    B("\\midrule")
    for name, _color, full in BASELINES:      # metric- and order-independent
        v = meta["baseline_per_instance_s"][name] * 1e3
        B(f"{full} & " + " & ".join([fmt_ms(v)] * 4) + " \\\\")
    B("\\bottomrule")
    B("\\end{tabular}")
    tabular = "\n".join(body)

    full = (
        "% Auto-generated by scripts/bench_step8_tikz.py -- needs \\usepackage{booktabs}\n"
        "\\begin{table}[t]\n\\centering\n"
        "\\caption{Average per-instance inference time at $K=53$ labels "
        "(enron), in milliseconds. The four ILP rows are the BOPOs search "
        "times plotted in the runtime figures; the lower block lists the "
        "baseline per-instance inference costs (independent of preference "
        "order and target metric). GLPK is measured only up to $K\\le31$ "
        "(prohibitively slow beyond), so its $K=53$ entries "
        "(\\textsuperscript{*}) are extrapolated from the least-squares "
        "power-law fit $c\\,K^{x}$; HiGHS values are measured.}\n"
        "\\label{tab:runtime-at-53}\n"
        + tabular + "\n\\end{table}\n")
    return full, tabular


def compile_table_preview(stem, tabular):
    if shutil.which("pdflatex") is None:
        return False
    doc = ("\\documentclass[border=6pt]{standalone}\n"
           "\\usepackage{booktabs}\n\\begin{document}\n"
           + tabular + "\n\\end{document}\n")
    with tempfile.TemporaryDirectory() as td:
        tex = Path(td) / f"{stem}.tex"
        tex.write_text(doc)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
                        tex.name], cwd=td, capture_output=True, text=True)
        pdf = Path(td) / f"{stem}.pdf"
        if pdf.exists():
            shutil.copy(pdf, OUTDIR / f"{stem}.pdf")
            return True
        return False


def compile_preview(stem, tikz):
    if shutil.which("pdflatex") is None:
        return False
    doc = ("\\documentclass[border=4pt]{standalone}\n"
           "\\usepackage{pgfplots}\\pgfplotsset{compat=1.16}\n"
           "\\begin{document}\n" + tikz + "\\end{document}\n")
    with tempfile.TemporaryDirectory() as td:
        tex = Path(td) / f"{stem}.tex"
        tex.write_text(doc)
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                            "-halt-on-error", tex.name], cwd=td,
                           capture_output=True, text=True)
        pdf = Path(td) / f"{stem}.pdf"
        if not pdf.exists():
            print(f"  ! pdflatex failed for {stem}:\n"
                  + "\n".join(r.stdout.splitlines()[-15:]))
            return False
        shutil.copy(pdf, OUTDIR / f"{stem}.pdf")
        if shutil.which("pdftoppm"):
            subprocess.run(["pdftoppm", "-png", "-r", "150",
                           str(OUTDIR / f"{stem}.pdf"),
                           str(OUTDIR / stem)], capture_output=True)
            # pdftoppm appends -1; normalise the name
            p1 = OUTDIR / f"{stem}-1.png"
            if p1.exists():
                p1.rename(OUTDIR / f"{stem}.png")
        return True


def main():
    meta = pickle.load((SCRATCH / "enron_bench_meta.pkl").open("rb"))
    all_rows = {order: load_rows(CSV[order]) for order in ("preorder", "partial")}
    for order in ("preorder", "partial"):
        rows = all_rows[order]
        for metric in ("Hamming", "Subset"):
            stem = f"runtime_{order}_{metric.lower()}"
            tikz = make_tikz(order, metric, rows, meta)
            (OUTDIR / f"{stem}.tex").write_text(tikz)
            ok = compile_preview(stem, tikz)
            print(f"wrote {stem}.tex" + ("  + preview png/pdf" if ok else ""))

    # per-instance runtime at K=53, one LaTeX table across all four figures
    full, tabular = make_table(all_rows, meta)
    (OUTDIR / "runtime_at_53.tex").write_text(full)
    ok = compile_table_preview("runtime_at_53", tabular)
    print("wrote runtime_at_53.tex" + ("  + preview pdf" if ok else ""))


if __name__ == "__main__":
    main()
